version: '3.8'

services:
  # MySQL Database
  mysql-db:
    image: mysql:8.0
    container_name: costume-rental-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: costume_rental_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - costume-rental-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  # User Service
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8081"
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - costume-rental-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 60s

  # Costume Service
  costume-service:
    build:
      context: .
      dockerfile: costume-service/Dockerfile
    container_name: costume-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8082"
    depends_on:
      mysql-db:
        condition: service_healthy
      supplier-service:
        condition: service_healthy
    networks:
      - costume-rental-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 60s

  # Bill Costume Service
  bill-costume-service:
    build:
      context: .
      dockerfile: bill-costume-service/Dockerfile
    container_name: bill-costume-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8083:8083"
    depends_on:
      mysql-db:
        condition: service_healthy
      user-service:
        condition: service_healthy
    networks:
      - costume-rental-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 60s

  # Supplier Service
  supplier-service:
    build:
      context: .
      dockerfile: supplier-service/Dockerfile
    container_name: supplier-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8084:8084"
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - costume-rental-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/actuator/health"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 60s

  # Import Bill Service
  import-bill-service:
    build:
      context: .
      dockerfile: import-bill-service/Dockerfile
    container_name: import-bill-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8085:8085"
    depends_on:
      mysql-db:
        condition: service_healthy
      user-service:
        condition: service_healthy
      costume-service:
        condition: service_healthy
    networks:
      - costume-rental-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/actuator/health"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 60s

  # Client Costume Rental (Frontend)
  client-costume-rental:
    build:
      context: .
      dockerfile: client-costume-rental/Dockerfile
    container_name: client-costume-rental
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      user-service:
        condition: service_healthy
      costume-service:
        condition: service_healthy
      supplier-service:
        condition: service_healthy
      bill-costume-service:
        condition: service_healthy
      import-bill-service:
        condition: service_healthy
    networks:
      - costume-rental-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 60s

volumes:
  mysql_data:

networks:
  costume-rental-network:
    driver: bridge
