apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: costume-rental
type: Opaque
data:
  # root password: "rootpassword" (base64 encoded)
  mysql-root-password: cm9vdHBhc3N3b3Jk
  # user password: "1234" (base64 encoded)  
  mysql-password: MTIzNA==
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: costume-rental
type: Opaque
data:
  # Database username: "root" (base64 encoded)
  db-username: cm9vdA==
  # Database password: "1234" (base64 encoded)
  db-password: MTIzNA==
