apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-costume-rental
  namespace: costume-rental
  labels:
    app: client-costume-rental
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-costume-rental
  template:
    metadata:
      labels:
        app: client-costume-rental
    spec:
      containers:
      - name: client-costume-rental
        image: client-costume-rental:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: costume-rental-config
        - secretRef:
            name: costume-rental-secret
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: client-costume-rental
  namespace: costume-rental
spec:
  selector:
    app: client-costume-rental
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
