apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: costume-rental
data:
  # Database configuration
  mysql-host: "mysql.costume-rental.svc.cluster.local"
  mysql-port: "3306"
  
  # Service URLs for inter-service communication
  user-service-url: "http://user-service.costume-rental.svc.cluster.local:8081"
  costume-service-url: "http://costume-service.costume-rental.svc.cluster.local:8082"
  bill-service-url: "http://bill-costume-service.costume-rental.svc.cluster.local:8083"
  supplier-service-url: "http://supplier-service.costume-rental.svc.cluster.local:8084"
  import-bill-service-url: "http://import-bill-service.costume-rental.svc.cluster.local:8085"
  
  # Application configuration
  spring-profiles-active: "kubernetes"
  logging-level: "INFO"
