apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplier-service
  namespace: costume-rental
  labels:
    app: supplier-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: supplier-service
  template:
    metadata:
      labels:
        app: supplier-service
        version: v1
    spec:
      containers:
      - name: supplier-service
        image: costume-rental/supplier-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8084
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: spring-profiles-active
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://$(MYSQL_HOST):$(MYSQL_PORT)/supplier_service_db?createDatabaseIfNotExist=true"
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: mysql-host
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: mysql-port
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db-password
        - name: LOGGING_LEVEL_ROOT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: logging-level
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: supplier-service
  namespace: costume-rental
  labels:
    app: supplier-service
spec:
  selector:
    app: supplier-service
  ports:
  - name: http
    port: 8084
    targetPort: 8084
    protocol: TCP
  type: ClusterIP
