apiVersion: v1
kind: Namespace
metadata:
  name: costume-rental
  labels:
    name: costume-rental
    app: costume-rental-system
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: costume-rental-quota
  namespace: costume-rental
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: costume-rental-limits
  namespace: costume-rental
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
